version: '3.3'

services:
  srv-mgr-db:
    image: yobasystems/alpine-mariadb:latest
    container_name: srv-mgr-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    networks:
      app-network:
        ipv4_address: 192.168.178.2
    volumes:
      - srv-mgr-db-storage:/var/lib/mysql

  srv-mgr-backend:
    build:
      context: .
      dockerfile: srv_dockerfile
    container_name: srv-mgr-backend
    restart: unless-stopped
    networks:
      app-network:
        ipv4_address: 192.168.178.3
    ports:
      - "446:80" 
    depends_on:
      - srv-mgr-db
    volumes:
      - ./app-code:/var/www/html
      - ./apache-conf:/etc/apache2/sites-available
      - ./php-conf:/usr/local/etc/php/
networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.178.0/24

volumes:
  srv-mgr-db-storage:
    external: true
